#!/bin/bash

set -x

if [[ $HOSTNAME == "node"* ]] ; then
su ds_user <<'EOF'
set -x
# Nodejs
export NODEJS_HOME=/usr/local/lib/nodejs/node-v"9.10.1"/bin
export PATH=$NODEJS_HOME:$PATH

cd app/ui

npm install
EOF
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
npm install
fi
