#!/bin/bash

set -x

if [[ $HOSTNAME == "node"* ]] ; then
su ds_user <<'EOF'
sudo chown -R ds_user /tmp/Powertrain2
cd /tmp/Powertrain2
sbt playUpdateSecret
sbt dist
EOF
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
cd /tmp/Powertrain2
sbt playUpdateSecret
sbt dist
fi
