#!/bin/bash

set -x

if [[ $HOSTNAME == "node"* ]] ; then
su ds_user <<'EOF'
cd /tmp/Powertrain2
sbt playUpdateSecret
sbt dist
EOF
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
sbt updateSecret
sbt dist
fi
